"""empty message

Revision ID: 23ce681ccaa0
Revises: ff91f0ae5b6b
Create Date: 2017-06-10 13:51:31.638562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23ce681ccaa0'
down_revision = 'ff91f0ae5b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_top',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('show', sa.Boolean(), nullable=True),
    sa.Column('nlink', sa.Text(), nullable=True),
    sa.Column('template', sa.String(length=64), nullable=True),
    sa.Column('seoKey', sa.String(length=200), nullable=True),
    sa.Column('seoDescription', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('category_pid')
    op.add_column('categorys', sa.Column('category_top_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categorys', 'category_top', ['category_top_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categorys', type_='foreignkey')
    op.drop_column('categorys', 'category_top_id')
    op.create_table('category_pid',
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('category_pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], [u'categorys.id'], name=u'category_pid_ibfk_1'),
    sa.ForeignKeyConstraint(['category_pid'], [u'categorys.id'], name=u'category_pid_ibfk_2'),
    sa.PrimaryKeyConstraint('category_id', 'category_pid'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('category_top')
    # ### end Alembic commands ###
