"""empty message

Revision ID: 3cb45d3944a4
Revises: 8a9d0b76aee7
Create Date: 2017-06-10 14:47:07.411747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb45d3944a4'
down_revision = '8a9d0b76aee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'categorys', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'category_id')
    # ### end Alembic commands ###
