"""empty message

Revision ID: be813c861f5d
Revises: 3cb45d3944a4
Create Date: 2017-06-10 15:19:54.861341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be813c861f5d'
down_revision = '3cb45d3944a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_top', sa.Column('sort', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_top', 'sort')
    # ### end Alembic commands ###
