"""empty message

Revision ID: ff91f0ae5b6b
Revises: 
Create Date: 2017-06-10 13:21:12.254596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff91f0ae5b6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_pid',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_pid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categorys.id'], ),
    sa.ForeignKeyConstraint(['category_pid'], ['categorys.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'category_pid')
    )
    op.add_column(u'categorys', sa.Column('category_attribute_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categorys', 'category_attribute', ['category_attribute_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categorys', type_='foreignkey')
    op.drop_column(u'categorys', 'category_attribute_id')
    op.drop_table('category_pid')
    # ### end Alembic commands ###
